config: ensure redis is working

diff --git a/.github/workflows/performance-tests.yml b/.github/workflows/performance-tests.yml
--- a/.github/workflows/performance-tests.yml
+++ b/.github/workflows/performance-tests.yml
@@ -32,10 +32,23 @@ jobs:
         cd docker
         docker build -t gameoflife-api:latest -f ../src/GameOfLife.API/Dockerfile ../
 
+    - name: Wait for Redis to Be Ready
+      run: |
+        for i in {1..10}; do
+          if docker exec redis redis-cli ping | grep -q PONG; then
+            echo "Redis is ready."
+            exit 0
+          fi
+          echo "Waiting for Redis to be ready..."
+          sleep 2
+        done
+        echo "Redis failed to start."
+        exit 1
+
     - name: Start API Container
       run: |
         docker run -d --name gameoflife-api -p 80:80 -p 443:443 --env Redis__Host=redis gameoflife-api:latest
-        sleep 30
+        sleep 10
         
     - name: Display API Logs
       run: docker logs gameoflife-api
